language: r

jobs:
  include:
  - r: oldrel
    os: linux
  - r: release
    os: linux
  - r: devel
    os: linux
  - r: oldrel
    os: osx
  - r: release
    os: osx

sudo: false

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
