// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// get_residuals
arma::vec get_residuals(const arma::mat& X, const arma::colvec& y, const int intercept);
RcppExport SEXP _orthogonalize_get_residuals(SEXP XSEXP, SEXP ySEXP, SEXP interceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const int >::type intercept(interceptSEXP);
    rcpp_result_gen = Rcpp::wrap(get_residuals(X, y, intercept));
    return rcpp_result_gen;
END_RCPP
}
// get_group_residuals
arma::vec get_group_residuals(const arma::mat& X, const arma::vec& y, const arma::ivec& GroupVec, const int intercept);
RcppExport SEXP _orthogonalize_get_group_residuals(SEXP XSEXP, SEXP ySEXP, SEXP GroupVecSEXP, SEXP interceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type GroupVec(GroupVecSEXP);
    Rcpp::traits::input_parameter< const int >::type intercept(interceptSEXP);
    rcpp_result_gen = Rcpp::wrap(get_group_residuals(X, y, GroupVec, intercept));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_orthogonalize_get_residuals", (DL_FUNC) &_orthogonalize_get_residuals, 3},
    {"_orthogonalize_get_group_residuals", (DL_FUNC) &_orthogonalize_get_group_residuals, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_orthogonalize(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
