# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_residuals_multi <- function(xList, yList, intercept, GroupList) {
    .Call(`_orthogonalize_get_residuals_multi`, xList, yList, intercept, GroupList)
}

get_residuals_single <- function(X, y, intercept, GroupVec) {
    .Call(`_orthogonalize_get_residuals_single`, X, y, intercept, GroupVec)
}

