# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_residuals <- function(X, y, intercept) {
    .Call(`_orthogonalize_get_residuals`, X, y, intercept)
}

get_group_residuals <- function(X, y, GroupVec, intercept) {
    .Call(`_orthogonalize_get_group_residuals`, X, y, GroupVec, intercept)
}

